export const REPOSITORIES_SEARCH_RESET = 'REPOSITORIES_SEARCH_RESET'
export const REPOSITORIES_SEARCH_KEYWORD = 'REPOSITORIES_SEARCH_KEYWORD'
export const GET_REPOSITORIES_BY_TOP_RATINGS = 'GET_REPOSITORIES_BY_TOP_RATINGS';
export const GET_REPOSITORIES_BY_MOST_RECENT_UPDATED = 'GET_REPOSITORIES_BY_MOST_RECENT_UPDATED'
export const GET_REPOSITORIES_BY_SEARCH_KEYWORDS = 'GET_REPOSITORIES_BY_SEARCH_KEYWORDS'
export const GET_REPOSITORY_ISSUES = 'GET_REPOSITORY_ISSUES'
export const ISSUES_RESET = 'ISSUES_RESET'